-- Run this script in your Supabase SQL Editor to create the tables

-- Clubs Table
CREATE TABLE IF NOT EXISTS clubs (
  "clubId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "clubName" TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  logo TEXT,
  "coverColor" TEXT,
  "meetingDay" TEXT,
  "meetingTime" TEXT,
  location TEXT,
  "contactEmail" TEXT,
  "foundedDate" TEXT,
  website TEXT
);

-- Students Table
CREATE TABLE IF NOT EXISTS students (
  "studentId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "rollNumber" TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  department TEXT NOT NULL,
  year INTEGER NOT NULL,
  avatar TEXT
);

-- Roles Table
CREATE TABLE IF NOT EXISTS roles (
  "roleId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "roleName" TEXT NOT NULL,
  "roleType" TEXT NOT NULL
);

-- Memberships Table
CREATE TABLE IF NOT EXISTS memberships (
  "membershipId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "studentId" INTEGER REFERENCES students("studentId") ON DELETE CASCADE,
  "clubId" INTEGER REFERENCES clubs("clubId") ON DELETE CASCADE,
  "roleId" INTEGER REFERENCES roles("roleId") ON DELETE CASCADE,
  "joinDate" TEXT NOT NULL
);

-- Budgets Table
CREATE TABLE IF NOT EXISTS budgets (
  "budgetId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "clubId" INTEGER REFERENCES clubs("clubId") ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL,
  subject TEXT,
  description TEXT,
  "attachmentUrls" TEXT[],
  "requestDate" TEXT
);

-- Events Table
CREATE TABLE IF NOT EXISTS events (
  "eventId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "clubId" INTEGER REFERENCES clubs("clubId") ON DELETE CASCADE,
  "eventName" TEXT NOT NULL,
  "eventDate" TEXT NOT NULL,
  venue TEXT NOT NULL,
  "maxParticipants" INTEGER NOT NULL,
  description TEXT,
  status TEXT
);

-- Registrations Table
CREATE TABLE IF NOT EXISTS registrations (
  "registrationId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" INTEGER REFERENCES events("eventId") ON DELETE CASCADE,
  "studentId" INTEGER REFERENCES students("studentId") ON DELETE CASCADE,
  "registrationDate" TEXT NOT NULL
);

-- Attendances Table
CREATE TABLE IF NOT EXISTS attendances (
  "attendanceId" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" INTEGER REFERENCES events("eventId") ON DELETE CASCADE,
  "studentId" INTEGER REFERENCES students("studentId") ON DELETE CASCADE,
  status TEXT NOT NULL,
  "checkInTime" TEXT NOT NULL
);

-- Event Coordinators Table
CREATE TABLE IF NOT EXISTS event_coordinators (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" INTEGER REFERENCES events("eventId") ON DELETE CASCADE,
  "studentId" INTEGER REFERENCES students("studentId") ON DELETE CASCADE
);

-- Set up Row Level Security (RLS) policies
-- Enable RLS for all tables but allow anonymous access for this app (since auth is custom via auth-context)
ALTER TABLE clubs FORCE ROW LEVEL SECURITY;
ALTER TABLE students FORCE ROW LEVEL SECURITY;
ALTER TABLE roles FORCE ROW LEVEL SECURITY;
ALTER TABLE memberships FORCE ROW LEVEL SECURITY;
ALTER TABLE budgets FORCE ROW LEVEL SECURITY;
ALTER TABLE events FORCE ROW LEVEL SECURITY;
ALTER TABLE registrations FORCE ROW LEVEL SECURITY;
ALTER TABLE attendances FORCE ROW LEVEL SECURITY;
ALTER TABLE event_coordinators FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all for anon" ON clubs;
DROP POLICY IF EXISTS "Enable all for anon" ON students;
DROP POLICY IF EXISTS "Enable all for anon" ON roles;
DROP POLICY IF EXISTS "Enable all for anon" ON memberships;
DROP POLICY IF EXISTS "Enable all for anon" ON budgets;
DROP POLICY IF EXISTS "Enable all for anon" ON events;
DROP POLICY IF EXISTS "Enable all for anon" ON registrations;
DROP POLICY IF EXISTS "Enable all for anon" ON attendances;
DROP POLICY IF EXISTS "Enable all for anon" ON event_coordinators;

CREATE POLICY "Enable all for anon" ON clubs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON roles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON memberships FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON budgets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON registrations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON attendances FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for anon" ON event_coordinators FOR ALL USING (true) WITH CHECK (true);
